import { MISSIONS } from '../src/core/data/missions';
import { RC_LIGHT_TABLE } from '../src/core/data/lights';
import { DEFAULT_RC_CONFIG, RcPipeline, type RcReadStage } from '../src/engine/RcPipeline';

const W=480,H=432, room=MISSIONS[0].rooms[0], lampSpec=RC_LIGHT_TABLE.oil_lamp, scale=Math.min(W/12,H/11), ox=Math.floor((W-room.width*scale)/2), oy=Math.floor((H-room.height*scale)/2);
type LampState='intact'|'damaged'|'broken';
const state={lampState:'intact' as LampState,playerPosition:{...room.playerSpawn},enemyPosition:{...room.enemySpawns[0]},enemyAngle:0,flashlightEnabled:true,animate:false,playerBlocker:true,enemyBlocker:true,sandbagBlockers:true,sparkFlashRemainingMs:0};
const view=document.querySelector<HTMLCanvasElement>('#view')!, status=document.querySelector<HTMLElement>('#status')!, probes=document.querySelector<HTMLElement>('#probes')!;
const sourceStages=['scene','occlusion','emission'] as const, pipelineStages=['seed','sdf','radiance','final'] as const;
const stageCanvases=Object.fromEntries([...sourceStages,...pipelineStages].map(id=>[id,document.querySelector<HTMLCanvasElement>(`#${id}`)!])) as Record<string,HTMLCanvasElement>;
let pipeline:RcPipeline;
declare global { interface Window { __rcIntroCopy?: {status:'running'|'done'|'error';error?:string;getState:()=>unknown;setState:(partial:Partial<typeof state>)=>void} } }
const api=()=>({status:'done' as const,getState:()=>({...state,sparkFlashActive:state.sparkFlashRemainingMs>0,rc:{...pipeline.state()}}),setState:(partial:Partial<typeof state>)=>Object.assign(state,partial)});

function image():ImageData{return new ImageData(W,H)}
function pixel(im:ImageData,x:number,y:number,r:number,g:number,b:number,a=255){if(x<0||y<0||x>=W||y>=H)return;const i=(y*W+x)*4;im.data[i]=r;im.data[i+1]=g;im.data[i+2]=b;im.data[i+3]=a}
function rect(im:ImageData,x:number,y:number,w:number,h:number,r:number,g:number,b:number){for(let py=Math.max(0,Math.floor(y));py<Math.min(H,Math.ceil(y+h));py++)for(let px=Math.max(0,Math.floor(x));px<Math.min(W,Math.ceil(x+w));px++)pixel(im,px,py,r,g,b)}
function disk(im:ImageData,cx:number,cy:number,rad:number,r:number,g:number,b:number){const rr=rad*rad;for(let y=Math.floor(cy-rad);y<=Math.ceil(cy+rad);y++)for(let x=Math.floor(cx-rad);x<=Math.ceil(cx+rad);x++)if((x-cx)**2+(y-cy)**2<=rr)pixel(im,x,y,r,g,b)}
function capsule(im:ImageData,p:{x:number;y:number}){const x=ox+p.x*scale,y=oy+p.y*scale;rect(im,x-scale*.18,y-scale*.35,scale*.36,scale*.7,0,0,0);disk(im,x,y-scale*.35,scale*.18,0,0,0);disk(im,x,y+scale*.35,scale*.18,0,0,0)}
function cone(im:ImageData,p:{x:number;y:number},angle:number){const cx=ox+p.x*scale,cy=oy+p.y*scale;for(let d=5;d<scale*4.5;d++){const half=.18+d*.12;for(let o=-half;o<=half;o++){const x=Math.round(cx+Math.cos(angle)*d-Math.sin(angle)*o),y=Math.round(cy+Math.sin(angle)*d+Math.cos(angle)*o);const fade=1-d/(scale*4.5);pixel(im,x,y,Math.round(220*fade),Math.round(225*fade),Math.round(185*fade))}}}
function drawScene(im:ImageData){const c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d')!;x.fillStyle='#08070c';x.fillRect(0,0,W,H);for(let y=0;y<room.height;y++)for(let xx=0;xx<room.width;xx++){const wall=room.tiles[y][xx]==='#';x.fillStyle=wall?((xx+y)%2?'#64261f':'#773126'):(y%2?'#281217':'#35161a');x.fillRect(ox+xx*scale,oy+y*scale,scale+1,scale+1);if(wall){x.strokeStyle='#a64a30';x.strokeRect(ox+xx*scale+2,oy+y*scale+2,scale-4,scale-4)}}
  for(const f of room.furniture??[]){x.fillStyle='#70543c';x.beginPath();x.ellipse(ox+f.tile.x*scale,oy+f.tile.y*scale,scale*.42,scale*.25,0,0,Math.PI*2);x.fill()}
  const lamp={x:5,y:1};x.fillStyle=state.lampState==='broken'?'#332827':state.lampState==='damaged'?'#df7935':lampSpec.colorHex;x.fillRect(ox+lamp.x*scale-scale*.12,oy+lamp.y*scale-scale*.25,scale*.24,scale*.5);
  if(state.flashlightEnabled){x.save();x.translate(ox+state.enemyPosition.x*scale,oy+state.enemyPosition.y*scale);x.rotate(state.enemyAngle);x.fillStyle='rgba(220,230,190,.08)';x.beginPath();x.moveTo(0,0);x.arc(0,0,scale*4.5,-.32,.32);x.fill();x.restore()}
  x.fillStyle='#e8dca0';x.fillRect(ox+state.playerPosition.x*scale-scale*.2,oy+state.playerPosition.y*scale-scale*.3,scale*.4,scale*.6);x.fillStyle='#586a52';x.fillRect(ox+state.enemyPosition.x*scale-scale*.22,oy+state.enemyPosition.y*scale-scale*.3,scale*.44,scale*.6);im.data.set(x.getImageData(0,0,W,H).data)}
function build(){const scene=image(),occ=image(),em=image();drawScene(scene);occ.data.fill(255);for(let y=0;y<room.height;y++)for(let x=0;x<room.width;x++)if(room.tiles[y][x]==='#')rect(occ,ox+x*scale,oy+y*scale,scale,scale,0,0,0);if(state.sandbagBlockers)for(const f of room.furniture??[])disk(occ,ox+f.tile.x*scale,oy+f.tile.y*scale,scale*.42,0,0,0);disk(occ,ox+5*scale,oy+scale,scale*.13,0,0,0);if(state.playerBlocker)capsule(occ,state.playerPosition);if(state.enemyBlocker)capsule(occ,state.enemyPosition);for(let i=3;i<em.data.length;i+=4)em.data[i]=255;if(state.lampState!=='broken'){const flicker=state.lampState==='damaged'?0.7:1;const hex=lampSpec.colorHex.slice(1),lr=parseInt(hex.slice(0,2),16),lg=parseInt(hex.slice(2,4),16),lb=parseInt(hex.slice(4,6),16);disk(em,ox+5*scale,oy+scale,Math.max(3,scale*lampSpec.radius*.045),Math.round(lr*lampSpec.intensity*flicker),Math.round(lg*lampSpec.intensity*flicker),Math.round(lb*lampSpec.intensity*flicker))}if(state.flashlightEnabled)cone(em,state.enemyPosition,state.enemyAngle);if(state.sparkFlashRemainingMs>0)disk(em,ox+5*scale,oy+scale,scale*.3,255,240,190);return{width:W,height:H,sceneColor:scene,occlusion:occ,emission:em,lightCount:Number(state.lampState!=='broken')+Number(state.flashlightEnabled)}}
function showSource(id:string,im:ImageData){const c=stageCanvases[id];c.width=W;c.height=H;c.getContext('2d')!.putImageData(im,0,0)}
async function copyStage(id:RcReadStage,boost=1){pipeline.debugShowStage(id,boost);const c=stageCanvases[id];c.width=W;c.height=H;const img=new Image();await new Promise<void>((ok,bad)=>{img.onload=()=>ok();img.onerror=()=>bad();img.src=view.toDataURL()});c.getContext('2d')!.drawImage(img,0,0)}
function luma(x:number,y:number){let v=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const [r,g,b]=pipeline.readPixel('final',ox+x*scale+dx,oy+y*scale+dy);v+=.299*r+.587*g+.114*b}return v/(9*255)}
let busy=false,last=performance.now();async function frame(now:number){requestAnimationFrame(frame);if(busy)return;busy=true;try{const dt=now-last;last=now;if(state.animate)state.enemyAngle=Math.sin(now*.0006*Math.PI)*.7;state.sparkFlashRemainingMs=Math.max(0,state.sparkFlashRemainingMs-dt);const f=build();pipeline.render(f,{...DEFAULT_RC_CONFIG,cascadeCount:Number((document.querySelector('#cascade') as HTMLSelectElement).value),lightScale:Number((document.querySelector('#lightScale') as HTMLInputElement).value),ambientIntensity:.01,twoLoop:true,ditherEnabled:false});showSource('scene',f.sceneColor);showSource('occlusion',f.occlusion);showSource('emission',f.emission);await copyStage('seed');await copyStage('sdf');await copyStage('radiance',3);await copyStage('final');pipeline.debugShowStage('final');const s=pipeline.state();probes.textContent=`lamp ${luma(5,1).toFixed(3)} | player ${luma(state.playerPosition.x,state.playerPosition.y).toFixed(3)} | enemy ${luma(4,4).toFixed(3)}\nleft sandbag ${luma(2,2).toFixed(3)} | right sandbag ${luma(7,2).toFixed(3)}\ncascades=${s.activeCascades} jfa=${s.jfaPasses} frame=${s.lastFrameTimeMs.toFixed(1)}ms degraded=${s.degraded} dither=${s.ditherEnabled}`;window.__rcIntroCopy=api()}catch(e){const message=e instanceof Error?e.message:String(e);window.__rcIntroCopy={...api(),status:'error',error:message};status.textContent=`ERROR ${message}`}finally{busy=false}}
try{pipeline=new RcPipeline(view,{cascadeCount:3,twoLoop:true,ditherEnabled:false,lightScale:1.6,ambientIntensity:.01});status.textContent='WebGL2 OK · real RC active';status.style.color='#78dd98';window.__rcIntroCopy={...api(),status:'running'};requestAnimationFrame(frame)}catch(e){const message=e instanceof Error?e.message:String(e);status.textContent=`ERROR ${message}`;window.__rcIntroCopy={status:'error',error:message,getState:()=>state,setState:partial=>Object.assign(state,partial)}}
document.querySelectorAll<HTMLButtonElement>('[data-lamp]').forEach(b=>b.onclick=()=>{state.lampState=b.dataset.lamp as LampState;document.querySelectorAll('[data-lamp]').forEach(x=>x.classList.toggle('active',x===b))});
(document.querySelector('#angle') as HTMLInputElement).oninput=e=>state.enemyAngle=Number((e.target as HTMLInputElement).value);(document.querySelector('#animate') as HTMLInputElement).onchange=e=>state.animate=(e.target as HTMLInputElement).checked;(document.querySelector('#flashlight') as HTMLInputElement).onchange=e=>state.flashlightEnabled=(e.target as HTMLInputElement).checked;(document.querySelector('#playerBlocker') as HTMLInputElement).onchange=e=>state.playerBlocker=(e.target as HTMLInputElement).checked;(document.querySelector('#enemyBlocker') as HTMLInputElement).onchange=e=>state.enemyBlocker=(e.target as HTMLInputElement).checked;(document.querySelector('#sandbags') as HTMLInputElement).onchange=e=>state.sandbagBlockers=(e.target as HTMLInputElement).checked;(document.querySelector('#spark') as HTMLButtonElement).onclick=()=>state.sparkFlashRemainingMs=75;
