import { voxelizeEllipsoid, selectCrater } from '../src/core/voxel/index.js';
import { intersectEllipsoid, stepDebris, type DebrisState } from '../src/core/physics/index.js';
import { acceptsNextNote, debrisCountForPower, HIT_WINDOW_SECONDS, isInHitWindow, timingGrade, timingPower } from '../src/intro/rhythm.js';
import { MIN_SCENERY_COUNTS, SCENERY_COUNTS, TERRAIN_LAYOUT } from '../src/intro/stageVisuals.js';
declare const process: { exitCode?: number };
const check=(name:string,value:boolean)=>{console.log(`${value?'PASS':'FAIL'} ${name}`);if(!value)process.exitCode=1;};
const model=voxelizeEllipsoid({x:2.8,y:3.35,z:1.9},40); check('surface-only model',model.cells.length>1000&&model.cells.length<2240);
const a=selectCrater(model,{x:-2.7,y:1.2,z:.5},7),b=selectCrater(model,{x:-2.7,y:1.2,z:.5},7);check('deterministic connected crater',a.removed.length>=12&&JSON.stringify(a)===JSON.stringify(b));
check('swept ellipsoid collision',intersectEllipsoid({x:-10,y:0,z:0},{x:10,y:0,z:0},{center:{x:0,y:0,z:0},radii:{x:2,y:3,z:2}})!==null);
const debris:DebrisState[]=[{active:true,sleeping:false,position:{x:0,y:2,z:0},previous:{x:0,y:2,z:0},velocity:{x:.1,y:0,z:0},age:0}];for(let i=0;i<301;i++)stepDebris(debris,1/60,0);check('debris sleeps or recycles',debris[0]!.sleeping);check('pool remains bounded',debris.length===1);
check('forgiving edge timing window',isInHitWindow(.1)&&isInHitWindow(.9)&&!isInHitWindow(.5)&&HIT_WINDOW_SECONDS>=.2);
check('timing boundaries',timingGrade(.08)==='PERFECT'&&timingGrade(.16)==='GOOD'&&timingGrade(.3)==='OK'&&timingGrade(.301)==='OFF BEAT');
check('off beat has power',timingPower('OFF BEAT')>0);
check('power monotonic',timingPower('PERFECT')>timingPower('GOOD')&&timingPower('GOOD')>timingPower('OK')&&timingPower('OK')>timingPower('OFF BEAT'));
check('power explicitly scales debris 20..64',debrisCountForPower(0)===20&&debrisCountForPower(.5)===42&&debrisCountForPower(1)===64);
const command=['PATA','PON','PATA','PON'] as const;check('correct off-beat note never cancels',acceptsNextNote(command,0,'PATA')&&timingGrade(.5)==='OFF BEAT');check('wrong order cancels',!acceptsNextNote(command,1,'PATA'));
check('Moloch height at least 4x mean unit',8.9/2.04>=4);
check('terrain tiles overlap into continuous floor',TERRAIN_LAYOUT.tilePitch<=TERRAIN_LAYOUT.tileFootprint);
check('terrain covers all actor positions',TERRAIN_LAYOUT.xMin<=-9&&TERRAIN_LAYOUT.xMax>=11&&TERRAIN_LAYOUT.zMin<=-2&&TERRAIN_LAYOUT.zMax>=2);
check('required sky-forest scenery categories',Object.entries(MIN_SCENERY_COUNTS).every(([category,minimum])=>SCENERY_COUNTS[category as keyof typeof SCENERY_COUNTS]>=minimum));
const army=[[-8,1.35],[-5.2,0],[-7.7,-1.45]],unitDiameter=2.1;const overlap=(a:number[],b:number[])=>Math.max(0,unitDiameter-Math.hypot(a[0]!-b[0]!,a[1]!-b[1]!))/unitDiameter;check('unit overlap at most 15 percent',Math.max(overlap(army[0]!,army[1]!),overlap(army[0]!,army[2]!),overlap(army[1]!,army[2]!))<=.15);
