// 10–14 hand-crafted region definitions.
// Each region is a JSON-style constant; runtime randomizes arrangement.

import type { RegionDef } from './region-types.js';
import { asRegionId, asElementId, asFactionId } from '../id.js';

export const REGION_DEFS: ReadonlyArray<RegionDef> = [
  {
    id: asRegionId('polar-shield'),
    name: 'Polar Shield Array',
    silhouette: 'ice-cap',
    resistance: asElementId('plasma'),
    weakness: asElementId('kinetic'),
    environmentalBonus: 'magnetic-arc',
    defense: { archetype: 'shield-ring', hp: 80, shield: 60, resistance: asElementId('plasma'), weakness: asElementId('kinetic'), behavior: 'shield' },
    factionSeed: asFactionId('arctic-coalition'),
    resourceWeights: { signal: 0.4, intelligence: 0.6 },
    visual: {
      primaryColor: '#a8c8ff',
      accentColor: '#4f6cff',
      geometryHints: ['dome', 'spike-array'],
      shaderUniforms: { auroraIntensity: 0.8 },
    },
  },
  {
    id: asRegionId('solar-megacity'),
    name: 'Solar Megacity',
    silhouette: 'megacity',
    resistance: asElementId('kinetic'),
    weakness: asElementId('corrosive'),
    environmentalBonus: 'heat-burst',
    defense: { archetype: 'turret-belt', hp: 100, shield: 30, resistance: asElementId('kinetic'), weakness: asElementId('corrosive'), behavior: 'turret' },
    factionSeed: asFactionId('corporate-bloc'),
    resourceWeights: { salvage: 0.5, intelligence: 0.5 },
    visual: {
      primaryColor: '#ffb86c',
      accentColor: '#ff5b3c',
      geometryHints: ['towers', 'solar-panels'],
      shaderUniforms: { glowIntensity: 1.2 },
    },
  },
  {
    id: asRegionId('storm-basin'),
    name: 'Perpetual Storm Basin',
    silhouette: 'oceanic-trench',
    resistance: asElementId('thermal'),
    weakness: asElementId('electric'),
    environmentalBonus: 'lightning-chain',
    defense: { archetype: 'satellite-web', hp: 60, shield: 50, resistance: asElementId('thermal'), weakness: asElementId('electric'), behavior: 'satellite' },
    factionSeed: asFactionId('storm-watchers'),
    resourceWeights: { energy: 0.7, biomass: 0.3 },
    visual: {
      primaryColor: '#3c8cff',
      accentColor: '#6cffff',
      geometryHints: ['spirals', 'platforms'],
      shaderUniforms: { turbulence: 1.5 },
    },
  },
  {
    id: asRegionId('mountain-fortress'),
    name: 'Mountain Fortress',
    silhouette: 'mountain',
    resistance: asElementId('plasma'),
    weakness: asElementId('gravity'),
    environmentalBonus: 'tunnel-network',
    defense: { archetype: 'bunker', hp: 140, shield: 40, resistance: asElementId('plasma'), weakness: asElementId('gravity'), behavior: 'shield' },
    factionSeed: asFactionId('highland-clans'),
    resourceWeights: { salvage: 0.6, intelligence: 0.4 },
    visual: {
      primaryColor: '#8a6c4a',
      accentColor: '#ffaa4a',
      geometryHints: ['peaks', 'bunkers'],
      shaderUniforms: { roughness: 0.95 },
    },
  },
  {
    id: asRegionId('orbital-hub'),
    name: 'Orbital Hub',
    silhouette: 'orbital-hub',
    resistance: asElementId('gravity'),
    weakness: asElementId('plasma'),
    environmentalBonus: 'dense-traffic',
    defense: { archetype: 'laser-grid', hp: 70, shield: 80, resistance: asElementId('gravity'), weakness: asElementId('plasma'), behavior: 'satellite' },
    factionSeed: asFactionId('space-corps'),
    resourceWeights: { signal: 0.5, intelligence: 0.5 },
    visual: {
      primaryColor: '#d4d8e8',
      accentColor: '#6cffff',
      geometryHints: ['rings', 'platforms'],
      shaderUniforms: { metalness: 0.9 },
    },
  },
  {
    id: asRegionId('subterranean-command'),
    name: 'Subterranean Command',
    silhouette: 'plains',
    resistance: asElementId('plasma'),
    weakness: asElementId('gravity'),
    environmentalBonus: 'scan-window',
    defense: { archetype: 'nuke-silo', hp: 160, shield: 20, resistance: asElementId('plasma'), weakness: asElementId('gravity'), behavior: 'nuclear' },
    factionSeed: asFactionId('silent-cabinet'),
    resourceWeights: { intelligence: 0.7, darkMatter: 0.3 },
    visual: {
      primaryColor: '#5a4a3a',
      accentColor: '#ff5b6c',
      geometryHints: ['flat', 'silos'],
      shaderUniforms: { roughness: 0.9 },
    },
  },
  {
    id: asRegionId('rebel-archipelago'),
    name: 'Rebel Archipelago',
    silhouette: 'archipelago',
    resistance: asElementId('emp'),
    weakness: asElementId('signal'),
    environmentalBonus: 'split-factions',
    defense: { archetype: 'decoy-fleet', hp: 50, shield: 30, resistance: asElementId('emp'), weakness: asElementId('signal'), behavior: 'decoy' },
    factionSeed: asFactionId('free-islands'),
    resourceWeights: { biomass: 0.5, signal: 0.5 },
    visual: {
      primaryColor: '#6caa8a',
      accentColor: '#ffaa4a',
      geometryHints: ['islands', 'towers'],
      shaderUniforms: { waveIntensity: 1.0 },
    },
  },
  {
    id: asRegionId('forest-belt'),
    name: 'Forest Belt',
    silhouette: 'forest',
    resistance: asElementId('kinetic'),
    weakness: asElementId('corrosive'),
    environmentalBonus: 'regrowth',
    defense: { archetype: 'jammer-net', hp: 60, shield: 40, resistance: asElementId('kinetic'), weakness: asElementId('corrosive'), behavior: 'jammer' },
    factionSeed: asFactionId('green-council'),
    resourceWeights: { biomass: 0.8, intelligence: 0.2 },
    visual: {
      primaryColor: '#4a8a4a',
      accentColor: '#aaff6c',
      geometryHints: ['trees', 'spores'],
      shaderUniforms: { fogIntensity: 1.2 },
    },
  },
  {
    id: asRegionId('volcanic-ridge'),
    name: 'Volcanic Ridge',
    silhouette: 'volcanic',
    resistance: asElementId('thermal'),
    weakness: asElementId('electric'),
    environmentalBonus: 'plume-cover',
    defense: { archetype: 'mine-field', hp: 80, shield: 10, resistance: asElementId('thermal'), weakness: asElementId('electric'), behavior: 'mine' },
    factionSeed: asFactionId('fire-worshippers'),
    resourceWeights: { energy: 0.6, salvage: 0.4 },
    visual: {
      primaryColor: '#ff5b3c',
      accentColor: '#ffaa4a',
      geometryHints: ['cones', 'rivers'],
      shaderUniforms: { glowIntensity: 1.4 },
    },
  },
  {
    id: asRegionId('desert-array'),
    name: 'Desert Solar Array',
    silhouette: 'desert',
    resistance: asElementId('emp'),
    weakness: asElementId('plasma'),
    environmentalBonus: 'scorch-amplify',
    defense: { archetype: 'railgun-belt', hp: 90, shield: 50, resistance: asElementId('emp'), weakness: asElementId('plasma'), behavior: 'battery' },
    factionSeed: asFactionId('solar-monks'),
    resourceWeights: { energy: 0.8, salvage: 0.2 },
    visual: {
      primaryColor: '#e8c88a',
      accentColor: '#ffd86c',
      geometryHints: ['panels', 'dunes'],
      shaderUniforms: { heatHaze: 1.0 },
    },
  },
  {
    id: asRegionId('blackout-zone'),
    name: 'Global Blackout Zone',
    silhouette: 'megacity',
    resistance: asElementId('digital'),
    weakness: asElementId('thermal'),
    environmentalBonus: 'no-comms',
    defense: { archetype: 'cyber-hunter', hp: 70, shield: 60, resistance: asElementId('digital'), weakness: asElementId('thermal'), behavior: 'jammer' },
    factionSeed: asFactionId('dead-grid'),
    resourceWeights: { signal: 0.7, intelligence: 0.3 },
    visual: {
      primaryColor: '#202028',
      accentColor: '#6cffff',
      geometryHints: ['dark-towers', 'antennae'],
      shaderUniforms: { emissiveIntensity: 0.4 },
    },
  },
  {
    id: asRegionId('fragmented-plains'),
    name: 'Fragmented Plains',
    silhouette: 'plains',
    resistance: asElementId('propaganda'),
    weakness: asElementId('cyber'),
    environmentalBonus: 'split-factions',
    defense: { archetype: 'mixed-belt', hp: 60, shield: 30, resistance: asElementId('signal'), weakness: asElementId('emp'), behavior: 'turret' },
    factionSeed: asFactionId('rival-cantons'),
    resourceWeights: { intelligence: 0.6, salvage: 0.4 },
    visual: {
      primaryColor: '#a8a878',
      accentColor: '#ff5b6c',
      geometryHints: ['walls', 'flags'],
      shaderUniforms: { roughness: 0.85 },
    },
  },
];

export const REGION_DEFS_BY_ID: Readonly<Record<string, RegionDef>> = Object.freeze(
  REGION_DEFS.reduce<Record<string, RegionDef>>((acc, r) => {
    acc[r.id] = r;
    return acc;
  }, {})
);