// Generated by scripts/process-intro-sprites.mjs. Do not edit.
export type IntroSpriteFrame = Readonly<{ id: string; x: number; y: number; width: number; height: number; pivot: readonly [number, number]; fallback?: string }>;
export type IntroSpriteAsset = Readonly<{ url: string; sha256: string; width: number; height: number; required: boolean; interpolation: 'nearest'; fps: number; frames: readonly IntroSpriteFrame[] }>;
export type IntroSpriteManifest = Readonly<Record<string, IntroSpriteAsset>>;

export const INTRO_SPRITE_MANIFEST = {
  "player": {
    "url": "/sprites/intro/player-knife.png",
    "sha256": "bf9a86e4e99ce645493bd32d91f2aa8407f3e7d23d9641ae73ac8ae39a66d085",
    "width": 512,
    "height": 512,
    "required": true,
    "interpolation": "nearest",
    "fps": 8,
    "frames": [
      {
        "id": "N.idle",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk0",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk1",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk2",
        "x": 192,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk3",
        "x": 256,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.attack0",
        "x": 320,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.attack1",
        "x": 384,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.attack2",
        "x": 448,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.idle",
        "x": 0,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk0",
        "x": 64,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk1",
        "x": 128,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk2",
        "x": 192,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk3",
        "x": 256,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.attack0",
        "x": 320,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.attack1",
        "x": 384,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.attack2",
        "x": 448,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.idle",
        "x": 0,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk0",
        "x": 64,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk1",
        "x": 128,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk2",
        "x": 192,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk3",
        "x": 256,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.attack0",
        "x": 320,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.attack1",
        "x": 384,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.attack2",
        "x": 448,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.idle",
        "x": 0,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk0",
        "x": 64,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk1",
        "x": 128,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk2",
        "x": 192,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk3",
        "x": 256,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.attack0",
        "x": 320,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.attack1",
        "x": 384,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.attack2",
        "x": 448,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.idle",
        "x": 0,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk0",
        "x": 64,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk1",
        "x": 128,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk2",
        "x": 192,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk3",
        "x": 256,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.attack0",
        "x": 320,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.attack1",
        "x": 384,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.attack2",
        "x": 448,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.idle",
        "x": 0,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk0",
        "x": 64,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk1",
        "x": 128,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk2",
        "x": 192,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk3",
        "x": 256,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.attack0",
        "x": 320,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.attack1",
        "x": 384,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.attack2",
        "x": 448,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.idle",
        "x": 0,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk0",
        "x": 64,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk1",
        "x": 128,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk2",
        "x": 192,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk3",
        "x": 256,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.attack0",
        "x": 320,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.attack1",
        "x": 384,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.attack2",
        "x": 448,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.idle",
        "x": 0,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ],
        "fallback": "W.idle"
      },
      {
        "id": "NW.walk0",
        "x": 64,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ],
        "fallback": "W.walk0"
      },
      {
        "id": "NW.walk1",
        "x": 128,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ],
        "fallback": "W.walk1"
      },
      {
        "id": "NW.walk2",
        "x": 192,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ],
        "fallback": "W.walk2"
      },
      {
        "id": "NW.walk3",
        "x": 256,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ],
        "fallback": "W.walk3"
      },
      {
        "id": "NW.attack0",
        "x": 320,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ],
        "fallback": "W.attack0"
      },
      {
        "id": "NW.attack1",
        "x": 384,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ],
        "fallback": "W.attack1"
      },
      {
        "id": "NW.attack2",
        "x": 448,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ],
        "fallback": "W.attack2"
      }
    ]
  },
  "patrol": {
    "url": "/sprites/intro/flashlight-patrol.png",
    "sha256": "fd5d598f4c9711fb7b1fa929093bf935576d4ea6b55a29d3d0fecff2163cbd39",
    "width": 384,
    "height": 512,
    "required": true,
    "interpolation": "nearest",
    "fps": 8,
    "frames": [
      {
        "id": "N.idle",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk0",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk1",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk2",
        "x": 192,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk3",
        "x": 256,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.alert",
        "x": 320,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.idle",
        "x": 0,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk0",
        "x": 64,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk1",
        "x": 128,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk2",
        "x": 192,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk3",
        "x": 256,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.alert",
        "x": 320,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.idle",
        "x": 0,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk0",
        "x": 64,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk1",
        "x": 128,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk2",
        "x": 192,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk3",
        "x": 256,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.alert",
        "x": 320,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.idle",
        "x": 0,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk0",
        "x": 64,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk1",
        "x": 128,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk2",
        "x": 192,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk3",
        "x": 256,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.alert",
        "x": 320,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.idle",
        "x": 0,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk0",
        "x": 64,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk1",
        "x": 128,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk2",
        "x": 192,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk3",
        "x": 256,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.alert",
        "x": 320,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.idle",
        "x": 0,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk0",
        "x": 64,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk1",
        "x": 128,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk2",
        "x": 192,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk3",
        "x": 256,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.alert",
        "x": 320,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.idle",
        "x": 0,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk0",
        "x": 64,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk1",
        "x": 128,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk2",
        "x": 192,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk3",
        "x": 256,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.alert",
        "x": 320,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.idle",
        "x": 0,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk0",
        "x": 64,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk1",
        "x": 128,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk2",
        "x": 192,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk3",
        "x": 256,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.alert",
        "x": 320,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      }
    ]
  },
  "lamp": {
    "url": "/sprites/intro/oil-lamp.png",
    "sha256": "f5f78b8386a0e55477ef74b9fbea6c0186ccf0f7b7f233c6d0b0c680d03a83cf",
    "width": 192,
    "height": 64,
    "required": true,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "lamp.0",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "lamp.1",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "lamp.2",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      }
    ]
  },
  "ground": {
    "url": "/sprites/intro/ground.png",
    "sha256": "7f4a9e26485748e52d86e6fa4db3b5984f33dcadba1f46ee3e40602c92b9d32b",
    "width": 48,
    "height": 48,
    "required": true,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "ground.0",
        "x": 0,
        "y": 0,
        "width": 48,
        "height": 48,
        "pivot": [
          24,
          24
        ]
      }
    ]
  },
  "brick": {
    "url": "/sprites/intro/brick.png",
    "sha256": "355f2190627bba644a8ab527c408266471ad5a14657b8835e1535866a9b68f2f",
    "width": 48,
    "height": 48,
    "required": true,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "brick.0",
        "x": 0,
        "y": 0,
        "width": 48,
        "height": 48,
        "pivot": [
          24,
          24
        ]
      }
    ]
  },
  "shikumen": {
    "url": "/sprites/intro/shikumen.png",
    "sha256": "029749b47a7ea732079d113fb2f2d588fa3ea132f010db67c879ce04647fe737",
    "width": 144,
    "height": 144,
    "required": true,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "shikumen.0",
        "x": 0,
        "y": 0,
        "width": 144,
        "height": 144,
        "pivot": [
          72,
          72
        ]
      }
    ]
  },
  "laundry": {
    "url": "/sprites/intro/laundry.png",
    "sha256": "d9fe46c01ddfb5ade52407e2569b27ec5a38d2691798e80f4fb0ea95b554576f",
    "width": 192,
    "height": 192,
    "required": false,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "laundry.0",
        "x": 0,
        "y": 0,
        "width": 192,
        "height": 192,
        "pivot": [
          96,
          96
        ]
      }
    ]
  },
  "spark": {
    "url": "/sprites/intro/spark.png",
    "sha256": "d8253887ea508a3bcf5a72d738dcb1fec06d1ee927fa56dd1557243d62a4bc09",
    "width": 256,
    "height": 64,
    "required": false,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "spark.0",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "spark.1",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "spark.2",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "spark.3",
        "x": 192,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      }
    ]
  },
  "glass": {
    "url": "/sprites/intro/glass.png",
    "sha256": "dd88c6aca32f3d89159219ee785842d75c42e7f00ad5648cc037fe4b938bb133",
    "width": 256,
    "height": 64,
    "required": false,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "glass.0",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "glass.1",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "glass.2",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "glass.3",
        "x": 192,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      }
    ]
  }
} as const satisfies IntroSpriteManifest;
