// Generated by scripts/process-intro-sprites.mjs. Do not edit.
export type IntroSpriteFrame = Readonly<{ id: string; x: number; y: number; width: number; height: number; pivot: readonly [number, number]; fallback?: string }>;
export type IntroSpriteAsset = Readonly<{ url: string; sha256: string; width: number; height: number; required: boolean; interpolation: 'nearest'; fps: number; frames: readonly IntroSpriteFrame[] }>;
export type IntroSpriteManifest = Readonly<Record<string, IntroSpriteAsset>>;

export const INTRO_SPRITE_MANIFEST = {
  "player": {
    "url": "/sprites/intro/player-knife.png",
    "sha256": "39a38c777ac10ed808c421eca0f479a6793cddeaeb9697877137da49221a5279",
    "width": 512,
    "height": 512,
    "required": true,
    "interpolation": "nearest",
    "fps": 8,
    "frames": [
      {
        "id": "N.idle",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk0",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk1",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk2",
        "x": 192,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk3",
        "x": 256,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.attack0",
        "x": 320,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.attack1",
        "x": 384,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.attack2",
        "x": 448,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.idle",
        "x": 0,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk0",
        "x": 64,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk1",
        "x": 128,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk2",
        "x": 192,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk3",
        "x": 256,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.attack0",
        "x": 320,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.attack1",
        "x": 384,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.attack2",
        "x": 448,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.idle",
        "x": 0,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk0",
        "x": 64,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk1",
        "x": 128,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk2",
        "x": 192,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk3",
        "x": 256,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.attack0",
        "x": 320,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.attack1",
        "x": 384,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.attack2",
        "x": 448,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.idle",
        "x": 0,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk0",
        "x": 64,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk1",
        "x": 128,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk2",
        "x": 192,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk3",
        "x": 256,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.attack0",
        "x": 320,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.attack1",
        "x": 384,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.attack2",
        "x": 448,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.idle",
        "x": 0,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk0",
        "x": 64,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk1",
        "x": 128,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk2",
        "x": 192,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk3",
        "x": 256,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.attack0",
        "x": 320,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.attack1",
        "x": 384,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.attack2",
        "x": 448,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.idle",
        "x": 0,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk0",
        "x": 64,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk1",
        "x": 128,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk2",
        "x": 192,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk3",
        "x": 256,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.attack0",
        "x": 320,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.attack1",
        "x": 384,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.attack2",
        "x": 448,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.idle",
        "x": 0,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk0",
        "x": 64,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk1",
        "x": 128,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk2",
        "x": 192,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk3",
        "x": 256,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.attack0",
        "x": 320,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.attack1",
        "x": 384,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.attack2",
        "x": 448,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.idle",
        "x": 0,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk0",
        "x": 64,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk1",
        "x": 128,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk2",
        "x": 192,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk3",
        "x": 256,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.attack0",
        "x": 320,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.attack1",
        "x": 384,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.attack2",
        "x": 448,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      }
    ]
  },
  "patrol": {
    "url": "/sprites/intro/flashlight-patrol.png",
    "sha256": "ff2579c4474056f1c1e3eed64b678c50c3a672bb0dfe9d59d1b9841a8a2b4d36",
    "width": 384,
    "height": 512,
    "required": true,
    "interpolation": "nearest",
    "fps": 8,
    "frames": [
      {
        "id": "N.idle",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk0",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk1",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk2",
        "x": 192,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.walk3",
        "x": 256,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "N.alert",
        "x": 320,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.idle",
        "x": 0,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk0",
        "x": 64,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk1",
        "x": 128,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk2",
        "x": 192,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.walk3",
        "x": 256,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NE.alert",
        "x": 320,
        "y": 64,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.idle",
        "x": 0,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk0",
        "x": 64,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk1",
        "x": 128,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk2",
        "x": 192,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.walk3",
        "x": 256,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "E.alert",
        "x": 320,
        "y": 128,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.idle",
        "x": 0,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk0",
        "x": 64,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk1",
        "x": 128,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk2",
        "x": 192,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.walk3",
        "x": 256,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SE.alert",
        "x": 320,
        "y": 192,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.idle",
        "x": 0,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk0",
        "x": 64,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk1",
        "x": 128,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk2",
        "x": 192,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.walk3",
        "x": 256,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "S.alert",
        "x": 320,
        "y": 256,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.idle",
        "x": 0,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk0",
        "x": 64,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk1",
        "x": 128,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk2",
        "x": 192,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.walk3",
        "x": 256,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "SW.alert",
        "x": 320,
        "y": 320,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.idle",
        "x": 0,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk0",
        "x": 64,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk1",
        "x": 128,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk2",
        "x": 192,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.walk3",
        "x": 256,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "W.alert",
        "x": 320,
        "y": 384,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.idle",
        "x": 0,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk0",
        "x": 64,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk1",
        "x": 128,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk2",
        "x": 192,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.walk3",
        "x": 256,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      },
      {
        "id": "NW.alert",
        "x": 320,
        "y": 448,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          54
        ]
      }
    ]
  },
  "lamp": {
    "url": "/sprites/intro/oil-lamp.png",
    "sha256": "785e05997b15679a611e75d4c481da0eae2d02ce7e15ff8ebdc2eec5ffb5a87b",
    "width": 192,
    "height": 64,
    "required": true,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "lamp.0",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "lamp.1",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "lamp.2",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      }
    ]
  },
  "ground": {
    "url": "/sprites/intro/ground.png",
    "sha256": "a22f0a2262d433eadaeff102b0b14e666e2d56ae0f00ec98da26c4e50fe42599",
    "width": 48,
    "height": 48,
    "required": true,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "ground.0",
        "x": 0,
        "y": 0,
        "width": 48,
        "height": 48,
        "pivot": [
          24,
          24
        ]
      }
    ]
  },
  "brick": {
    "url": "/sprites/intro/brick.png",
    "sha256": "a2b6a09945e45ddef86bec104ab83680dd935cd5cc593577baf95ed5da75b913",
    "width": 48,
    "height": 48,
    "required": true,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "brick.0",
        "x": 0,
        "y": 0,
        "width": 48,
        "height": 48,
        "pivot": [
          24,
          24
        ]
      }
    ]
  },
  "shikumen": {
    "url": "/sprites/intro/shikumen.png",
    "sha256": "955a0e7eadde9e7912f9c1d43310ab7ef237414e084a938dd4a61530630a7123",
    "width": 144,
    "height": 144,
    "required": true,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "shikumen.0",
        "x": 0,
        "y": 0,
        "width": 144,
        "height": 144,
        "pivot": [
          72,
          72
        ]
      }
    ]
  },
  "laundry": {
    "url": "/sprites/intro/laundry.png",
    "sha256": "d8dd20630599541f1eadc13029a793f78cef7402a95c1fb9228088f1aab5d598",
    "width": 192,
    "height": 192,
    "required": false,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "laundry.0",
        "x": 0,
        "y": 0,
        "width": 192,
        "height": 192,
        "pivot": [
          96,
          96
        ]
      }
    ]
  },
  "spark": {
    "url": "/sprites/intro/spark.png",
    "sha256": "b9d9f810818176c7aeeed54b6cfc11eb49e82bbfe48cadb76cc09ccd92f29655",
    "width": 256,
    "height": 64,
    "required": false,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "spark.0",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "spark.1",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "spark.2",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "spark.3",
        "x": 192,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      }
    ]
  },
  "glass": {
    "url": "/sprites/intro/glass.png",
    "sha256": "486f1eac8679d345ba26df595ad7fea1c188ca53ce60a1aa873ed72ef466d38b",
    "width": 256,
    "height": 64,
    "required": false,
    "interpolation": "nearest",
    "fps": 0,
    "frames": [
      {
        "id": "glass.0",
        "x": 0,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "glass.1",
        "x": 64,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "glass.2",
        "x": 128,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      },
      {
        "id": "glass.3",
        "x": 192,
        "y": 0,
        "width": 64,
        "height": 64,
        "pivot": [
          32,
          32
        ]
      }
    ]
  }
} as const satisfies IntroSpriteManifest;
