this._visible = false;
music_bo0 = new Sound(this);
music_bo0.attachSound("bo0");
music_bo1 = new Sound(this);
music_bo1.attachSound("bo1");
music_bo2 = new Sound(this);
music_bo2.attachSound("bo2");
music_bo3 = new Sound(this);
music_bo3.attachSound("bo3");
music_bo4 = new Sound(this);
music_bo4.attachSound("bo4");
music_beam1 = new Sound(this);
music_beam1.attachSound("snd_beam1");
music_beam2 = new Sound(this);
music_beam2.attachSound("snd_beam2");
music_beam3 = new Sound(this);
music_beam3.attachSound("snd_beam3");
music_beam4 = new Sound(this);
music_beam4.attachSound("snd_beam4");
music_beam5 = new Sound(this);
music_beam5.attachSound("snd_beam5");
music_beam6 = new Sound(this);
music_beam6.attachSound("snd_beam6");
music_axe1 = new Sound(this);
music_axe1.attachSound("snd_axe1");
music_bs1 = new Sound(this);
music_bs1.attachSound("snd_bs1");
music_nt = new Sound(this);
music_nt.attachSound("nt");
music_msdie = new Sound(this);
music_msdie.attachSound("msdie");
music_gsp = new Sound(this);
music_gsp.attachSound("gsp");
music_s_wlp = new Sound(this);
music_s_wlp.attachSound("s_wlp");
music_minigun = new Sound(this);
music_minigun.attachSound("minigun");
music_minigun1 = new Sound(this);
music_minigun1.attachSound("minigun1");
music_minigun2 = new Sound(this);
music_minigun2.attachSound("minigun2");
music_gsq = new Sound(this);
music_gsq.attachSound("gsq");
music_dj = new Sound(this);
music_dj.attachSound("dj");
music_fd = new Sound(this);
music_fd.attachSound("fdfs");
music_fyp = new Sound(this);
music_fyp.attachSound("fyp");
music_if = new Sound(this);
music_if.attachSound("if");
music_bcarnon = new Sound(this);
music_bcarnon.attachSound("bcarnon");
music_gpxn1 = new Sound(this);
music_gpxn1.attachSound("gpxn1");
music_gpxn2 = new Sound(this);
music_gpxn2.attachSound("gpxn2");
music_gpxn3 = new Sound(this);
music_gpxn3.attachSound("gpxn3");
music_gppp = new Sound(this);
music_gppp.attachSound("gppp");
music_hwq = new Sound(this);
music_hwq.attachSound("hwq");
music_hjd = new Sound(this);
music_hjd.attachSound("hjd");
music_hjf = new Sound(this);
music_hjf.attachSound("hjf");
music_ambac = new Sound(this);
music_ambac.attachSound("ambac");
music_pow = new Sound(this);
music_pow.attachSound("pow");
music_carnon = new Sound(this);
music_carnon.attachSound("carnon");
music_sniper = new Sound(this);
music_sniper.attachSound("sniper");
music_sniperf = new Sound(this);
music_sniperf.attachSound("sniperf");
music_boom = new Sound(this);
music_boom.attachSound("boom");
music_gsqs = new Sound(this);
music_gsqs.attachSound("gsqs");
music_sgsp = new Sound(this);
music_sgsp.attachSound("sgsp");
music_zdfs = new Sound(this);
music_zdfs.attachSound("zdfs");
music_gjk = new Sound(this);
music_gjk.attachSound("gjk");
music_fly = new Sound(this);
music_fly.attachSound("fly");
music_rush = new Sound(this);
music_rush.attachSound("rush");
music_lockon = new Sound(this);
music_lockon.attachSound("lockon");
music_lockff = new Sound(this);
music_lockff.attachSound("lockff");
music_bthit = new Sound(this);
music_bthit.attachSound("bthit");
music_bit = new Sound(this);
music_bit.attachSound("bit");
music_bit_n11 = new Sound(this);
music_bit_n11.attachSound("bit_n11");
music_dii = new Sound(this);
music_dii.attachSound("dii");
music_du = new Sound(this);
music_du.attachSound("du");
music_lost = new Sound(this);
music_lost.attachSound("lost");
music_dangX3 = new Sound(this);
music_dangX3.attachSound("dangX3");
music_warning = new Sound(this);
music_warning.attachSound("warning");
music_snd_hxb = new Sound(this);
music_snd_hxb.attachSound("snd_hxb");
music_machine1 = new Sound(this);
music_machine1.attachSound("machine1");
music_snd_launch0 = new Sound(this);
music_snd_launch0.attachSound("snd_launch0");
music_snd_launch1 = new Sound(this);
music_snd_launch1.attachSound("snd_launch1");
music_snd_launch2 = new Sound(this);
music_snd_launch2.attachSound("snd_launch2");
music_snd_launch3 = new Sound(this);
music_snd_launch3.attachSound("snd_launch3");
music_snd_launch4 = new Sound(this);
music_snd_launch4.attachSound("snd_launch4");
music_snd_gjk2 = new Sound(this);
music_snd_gjk2.attachSound("snd_gjk2");
music_snd_jiqi = new Sound(this);
music_snd_jiqi.attachSound("snd_jiqi");
music_snd_hphf = new Sound(this);
music_snd_hphf.attachSound("snd_hphf");
