/**
 * Offline bake: distill GGX teacher → decoder weights, write src/engine/baked.ts.
 * Run: npm run bake
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { LATENT_RESOLUTION, MLP_PARAM_COUNT, TRAIN_STEPS } from '../src/core/constants'
import { encodeLatent, materialAt } from '../src/core/material'
import { trainDecoder } from '../src/core/train'

const here = dirname(fileURLToPath(import.meta.url))
const outPath = join(here, '..', 'src', 'engine', 'baked.ts')

console.log(`baking decoder: ${TRAIN_STEPS} steps, latent ${LATENT_RESOLUTION}²×8`)
const t0 = Date.now()
const { weights, history, finalVal } = trainDecoder({
  onStep: (step, loss, lr) => {
    console.log(`  step ${String(step).padStart(5)}  trainLogL1=${loss.toFixed(5)}  lr=${lr.toExponential(2)}`)
  },
})
const ms = Date.now() - t0
console.log(`done in ${(ms / 1000).toFixed(1)}s  val log-L1=${finalVal.toFixed(5)}  params=${MLP_PARAM_COUNT}`)

const latent: number[] = []
for (let y = 0; y < LATENT_RESOLUTION; y++) {
  for (let x = 0; x < LATENT_RESOLUTION; x++) {
    const u = (x + 0.5) / LATENT_RESOLUTION
    const v = (y + 0.5) / LATENT_RESOLUTION
    const z = encodeLatent(materialAt([u, v]))
    latent.push(...z)
  }
}

const body = `/* eslint-disable */
/** Auto-generated by scripts/bake.ts — do not edit by hand. */
export const BAKED_VAL_L1 = ${JSON.stringify(Number(finalVal.toFixed(6)))}
export const BAKED_STEPS = ${TRAIN_STEPS}
export const BAKED_HISTORY = ${JSON.stringify(history.map((h) => Number(h.toFixed(6))))}
export const BAKED_WEIGHTS: number[] = ${JSON.stringify(Array.from(weights.data).map((x) => Number(x.toFixed(8))))}
export const BAKED_LATENT: number[] = ${JSON.stringify(latent.map((x) => Number(x.toFixed(6))))}
`

writeFileSync(outPath, body)
console.log(`wrote ${outPath}`)
